### ISSUE TITLE
Investigate inconsistent behavior of simulator + VM combination - huge latency in the reception of messages

### ISSUE THREAD

**Issue by juampehidalgo** [ucatie/CarND-Capstone#13]

**Comment by juampehidalgo** [comment]
During the testing of the controller implementation (currently in a separate branch), logs showed huge latency issues in the communication between the simulator and the ROS running within a VM. This would be experienced as /current_velocity topic not carrying updated car reading for long periods of time, hence halting the operation of the controller.

This issue seems to be widespread as per several discussions in the capstone project slack channel.

Propose to test a couple of configurations and decide best setup:
(1) Run both simulator and VM on same machine (sim on host OS, ROS on guest) and modify CONTROL_RATE (currently at 50 Hz) and topic message queues to try and find a working configuration

(2) Run Simulator and VM on separate machines (sim running on independent machine, ROS running on VM on separate machine, direct Ethernet bridge between both) to verify if this is due to machine load / thread scheduling issues

(3) Perform a native install of ROS a repeat test (2) --> this would require fixing Gazebo version issues as per default kinetic packages

**Comment by fscbr** [comment]
To reduce used computation power, it could help to add sleeps in the callback functions. They would not be processed so often and therefore would use less resources. F.ex. in tl_detector its should not be required to process each image of the camera

**Comment by fscbr** [comment]
using the system on a slow laptop running ubuntu in an vm it showed great improvement if the update rates and queue sizes are optimized. I dont see a need for a queue size larger 1.
messages should only be published if a change occured. Except the dbw_node which integrates over time. The update rate of that node should be the same frequency like telemetry is called in the server.py

**Comment by juampehidalgo** [comment]
Seems that udacity updated the code to publish the /base_waypoints topic just once... being this the major contributor to system load.

All team members seem to be able to run both ROS and sim on same computers, so closing as the original problem is related to bad overall quality of udacity code.
