### ISSUE TITLE
create augmentation for real traffic light images

### ISSUE THREAD

**Issue by fscbr** [ucatie/CarND-Capstone#16]

**Comment by fscbr** [comment]
to be able to train a FCN we need augmentation for traindata. An easy way is to use sloth.
these steps are required:
1. download and install sloth (python setup install)
2. unpack the  bag_dump_just_traffic_light.zip
3. cd bag_dump_just_traffic_light
4. start sloth using the capstoneconfig.py (sloth --config capstoneconfig.py
5. open in sloth the augmentation file sloth_capstone_real_data.yaml
for each image you want to add you need to select a label and mark the rectangle in the image
6. save and upload the yaml file.

I added already an example yaml containing some images all ready

**Comment by informramiz** [comment]
@fscbr Just pushed updated `yaml file` with red, green, yellow and unidentified images annotated.
