### ISSUE TITLE
react on traffic waypoint event

### ISSUE THREAD

**Issue by fscbr** [ucatie/CarND-Capstone#2]
if a traffic waypoint has been received and its close, car has to stop. Waypoint list target velocities have to reflect slow down until the car stops in front of the traffic light. When to accelerate again? When the traffic waypoint message is not received anymore?

**Comment by SebastianNi** [comment]
traffic_waypoint contains just an integer value. I assume this integer value should be 0 for red, 1 for yellow. In case of green, no message should be send at all. If the status of the traffic light is yellow, the waypoint updater node should determine if the distance to the traffic light is enough to stop the car or if it should keep on driving. In case of red, it should slow down anyway. This means we need the position of the traffic light first. I guess the traffic light position is contained in the obstacle_waypoint topic.
