### ISSUE TITLE
create TL ground thruth

### ISSUE THREAD

**Issue by fscbr** [ucatie/CarND-Capstone#8]
let the car drive around and record ground truth images required to train the classifier.

**Comment by fscbr** [comment]
In order to help you acquire an accurate ground truth data source for the traffic light classifier, the Udacity simulator publishes the location and current color state of all traffic lights in the simulator to the /vehicle/traffic_lights topic. This state can be used to generate classified images

**Comment by abes975** [comment]
If I'm not wrong we don't have to classify them manually..as status of traffic light is present in the topic
 /vehicle/traffic_lights

**Comment by fscbr** [comment]
yes, you are right, the topic can be used  for the  ground truth  classifications

**Comment by fscbr** [comment]
tl_detector is able to produce data and save it. heading of the car must be close to the way point orientation, otherwise the image does not contain the traffic light.
If this is a problem, more work has to be spent to find the angle where to look to the left or right
